### ISSUE TITLE
Is it possible to handle clob data

### ISSUE THREAD

**Issue by saridsa1** [soulwing/fluent-jdbc#3]
Is it possible to handle CLOB data using this API? if it is not then is there a way to extend the functionality to do so?

**Comment by ceharris** [comment]
I haven't really added any LOB support because I haven't needed it for my own use, but it's easy enough to add at least some basic support.  I created issue #4 for it which I think I can probably finish today.

LOB support varies a great deal by JDBC driver vendor. What database are you using?

**Comment by ceharris** [comment]
LOB support was added in version 1.2
